name: Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      # set git config to avoid asking for user name and email
    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "mail@kewan.fr"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build
    - run: cp dist/ _site/
      
    - run: |
        chmod -c -R +rX "_site/" | while read line; do
          echo "::warning title=Invalid file permissions automatically fixed::$line"
        done

    # 👇 Store the dist folder
    - uses: actions/upload-pages-artifact@v3
      
  
  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      contents: write
      id-token: write
      pages: write

    environment:
      name: github-pages
      url: ${{ steps.deploy-to-pages.outputs.page_url }}
    
    steps:
    - name: deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4