name: Deploy
on:
  push:
    branches:
      - main

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      # set git config to avoid asking for user name and email
    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "mail@kewan.fr"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run deploy
